---
# tasks file for piz-docker

- name: Pull nginx container
  community.docker.docker_image:
    name: docker.io/nginx
    source: pull
  tags: ['nginx']

- name: Ensure www data is present
  copy:
    src: www/
    dest: /srv/docker/www/
    owner: root
    group: root
    mode: 0644
    directory_mode: 0755
  tags: ['nginx']

- name: Create nginx container
  community.docker.docker_container:
    name: nginx
    image: docker.io/nginx
    state: started
    volumes:
      - '/srv/docker/www:/usr/share/nginx/html:ro'
    ports:
      - '8088:80'
  tags: ['nginx']

- name: Check if nginx container is working
  shell: 'curl --fail "http://localhost:8088" | grep -i "piz da peres"'
